# Generated by Django 5.2.4 on 2025-07-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('tech', 'Técnico'), ('client', 'Cliente')], default='client', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('can_add_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('blog_url', models.URLField(verbose_name='URL de blogs')),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('precioConImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidadSeleccionada', models.IntegerField(default=0)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraRecurrente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_comprarecurrente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=2000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
                ('imagenCurso', models.ImageField(null=True, upload_to='curso/')),
            ],
            options={
                'db_table': 'users_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioTotalProducto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'users_detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('idEntrega', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPreparado', models.DateTimeField(blank=True, null=True)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('estadoEntrega', models.CharField(choices=[('preparado', 'Preparado'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='preparado', max_length=20)),
            ],
            options={
                'db_table': 'users_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateField(blank=True, null=True)),
                ('day_end', models.DateField(blank=True, null=True)),
                ('dias', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'users_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodoP', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_metodopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloCurso',
            fields=[
                ('idModulo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('descripcion', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'users_modulocurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='portafolio/')),
            ],
            options={
                'db_table': 'users_portafolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('descripcionProducto', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCaducidad', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'db_table': 'users_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=2000)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('idRegistroVenta', models.AutoField(primary_key=True, serialize=False)),
                ('serieVenta', models.CharField(max_length=50)),
                ('numVenta', models.CharField(max_length=50)),
                ('horaVenta', models.TimeField(auto_now_add=True)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numCuotas', models.IntegerField(default=1)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoVenta', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_registroventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Activo'), ('closed', 'Eliminado')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Asistencia',
                'verbose_name_plural': 'Tipos de Asistencia',
                'db_table': 'users_asistencia',
                'ordering': ['tipo_asistencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('idTipoC', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_tipocomprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('tiempoEntrega', models.IntegerField(help_text='Tiempo en días')),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('estadoCategoria', models.BooleanField(default=True)),
                ('fechaCreacionCategoria', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionCategoria', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('idSub', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIcasoftWeb.categoria')),
            ],
            options={
                'db_table': 'users_subcategoria',
                'managed': True,
            },
        ),
    ]
