# Generated by Django 5.2.3 on 2025-07-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIcasoftWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'managed': False},
        ),
    ]
